spring:
  datasource:
    url: jdbc:jtds:sqlserver://ALDEVAN-NT:1433/Clismetra
    username: ${APG_DATABASE_USERNAME}
    password: ${APG_DATABASE_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
apg:
  company:
    name: Clismetra
  printers:
    password-printer:
      name: EPSON L3110 Series